### ISSUE TITLE
Better handling of media queries

### ISSUE THREAD

**Issue by rawksteady** [rawksteady/flexer#1]
Right now I'm wrapping everything in `@each` loops and `@media` queries, even if that current breakpoint is `0`. Ideally I'd want a `@mixin` (I think) which doesn't print a media query if a certain given breakpoint is `0`. One way could be doing `@if` statements within the `@mixin` (or even the current `@each` loops) itself but I can't shake the feeling that there is a much neater way of doing it. Very much open to suggestions!

[&rarr; flexer.scss:175](https://github.com/rawksteady/flexer/blob/09201dc597592532a7062b1af76ba49228687149/flexer.scss#L175)

So essentially this:
```css
@media (min-width: 0) {
    .sm\:d-f { display: flex; }
}
@media (min-width: 500px) {
    .md:\d-f { display: flex; }
}
...
```

Becomes this:
```css
.sm\:d-f { display: flex; }
@media (min-width: 500px) {
    .md\:d-f { display: flex; }
}
...
```

Not that it's needed right now since this is a quick n' dirty testing/prototyping tool but it never hurts to make things solid and add sparkles.
